# Generated by Django 5.2.4 on 2025-07-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_avatar_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Optional', null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
    ]
